services:
  app:
    build: .
    volumes:
      - ./images:/project/images

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./static:/web:ro
      - ./images:/project/images:ro