server {
    listen 8080;
    server_name _;
    # client_body_buffer_size 6M;
    client_max_body_size 20M;
    root /web;
    location / {
        proxy_pass http://app:8000;
    }
    # location /upload {
    #     proxy_pass http://app:8000;
    # }
}
